"""image table, avatar_url in user table

Revision ID: 596f6f8d6d38
Revises: 8c46d3943054
Create Date: 2020-03-24 23:27:15.359384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596f6f8d6d38'
down_revision = '8c46d3943054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('like_flag', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_timestamp'), 'image', ['timestamp'], unique=False)
    op.add_column('user', sa.Column('avatar_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_url')
    op.drop_index(op.f('ix_image_timestamp'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
